---
name: Bay
surname: Berry
position: "MSc Student - Laboratoire de Dynamique et Gestion Intégrée des Zones Côtières"
address: "Université du Québec à Rimouski, Québec"
profilepic: "./img/bay.jpg"
phone: +902 997 1894
email: "bay.berry@uqar.ca"
github: bberry8
orcid: 0000-0001-8865-9800
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
docname: CV
output: vitae::awesomecv
lang: fr
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)


pkgs <- c('vitae' ,'here' ,'tinytex' ,'tibble' ,'glue' ,'rmarkdown' ,'dplyr', 'readr' ,'yaml', 'r2symbols')
xfun::pkg_attach2(pkgs)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data sctructure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative Filepaths
             ,'readr'     # Data Loading
             ,'tidyverse' # Needed for bind_rows and whatever
             ,'scholar'   # Updating publications from google scholar
             ,'kableExtra'# Adding technicalskills table
             ,'r2symbols'
            )
library(magrittr)
# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
lapply(packages, library, character.only = TRUE) %>%
  invisible()

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}
education %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

# Experience

```{r Experience, results = "asis"}

experience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )

```

\pagebreak

# Skills

\begin{cvskills}
  \cvskill
    {Data Science}
    {R, ArcGIS, QGIS}

  \cvskill
    {Research}
    {Coastal geomorphology, permafrost, geospatial analysis}

  \cvskill
    {Languages}
    {English/French (bilingual)}
\end{cvskills}

# Awards

```{r AWARDS}

awards %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

# Publications and Presentations

```{r JOUNRALARTICLES}
bib <- bibliography_entries("publications.bib") %>%
  arrange(desc(issued))

bib$`container-title` <- str_to_sentence(bib$`container-title`, locale = "en")

bib
  
```
